ci: remove images: Push to main via ssh
Signed-off-by: John Andersen <johnandersenpdx@gmail.com>

diff --git a/.github/workflows/remove_images.yml b/.github/workflows/remove_images.yml
--- a/.github/workflows/remove_images.yml
+++ b/.github/workflows/remove_images.yml
@@ -24,6 +24,7 @@ jobs:
         REPO_URL: https://github.com/intel/dffml
         BRANCH: master
         GIT_FILTER_REPO_PATHS: /tmp/git-filter-repo-paths
+        SSH_DFFML_GH_PAGES: ${{ secrets.SSH_DFFML_GH_PAGES }}
       shell: bash -xe {0}
       run: |
         git init
@@ -40,10 +41,28 @@ jobs:
         EOF
         git filter-repo --force --invert-paths --paths-from-file $GIT_FILTER_REPO_PATHS
         git log --stat | grep -E '\.png|\.jpeg|\.jpg|\.gif'
-    - name: Push
-      env:
-        BRANCH: main
-      shell: bash -xe {0}
-      run: |
-        git checkout -b $BRANCH
-        git push -u origin $BRANCH
+
+        export GIT_SSH_COMMAND='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
+
+        TEMP_DIRS=()
+
+        function cleanup_temp_dirs() {
+          for temp_dir in ${TEMP_DIRS[@]}; do
+            rm -rf "${temp_dir}"
+          done
+        }
+
+        # Clean up temporary directories on exit
+        trap cleanup_temp_dirs EXIT
+
+        ssh_key_dir="$(mktemp -d)"
+        TEMP_DIRS+=("${ssh_key_dir}")
+        mkdir -p ~/.ssh
+        chmod 700 ~/.ssh
+        python -c "import pathlib, base64, os; keyfile = pathlib.Path(\"${ssh_key_dir}/github\").absolute(); keyfile.write_bytes(b''); keyfile.chmod(0o600); keyfile.write_bytes(base64.b32decode(os.environ['SSH_DFFML_GH_PAGES']))"
+        ssh-keygen -y -f "${ssh_key_dir}/github" > "${ssh_key_dir}/github.pub"
+        export GIT_SSH_COMMAND="${GIT_SSH_COMMAND} -o IdentityFile=${ssh_key_dir}/github"
+
+        git remote set-url origin git@github.com:intel/dffml
+        git checkout -b main
+        git push -u origin main
